---
# (c) Copyright IBM Corporation 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

# File: roles/runMQCmds/defaults/main.yml

# defaults file for role_runMQCmds
#
# As Ansible recommends that users do not change the supplied default values, the sample playbooks 
# show numerous ways of customizing the default values by specifying them as argument overrides on the 
# runMQCmds role. However, given the nature of some argument values, it would be acceptable for users 
# to replace default values with user-specific values as this may help reduce administrative overhead.

cmds_file_name: ../cmds_files/mq_crud_yaml_cmds.yml
webserver_addr: my.mqweb.server.address
webserver_port: 9443
api_userid: mqadmin
api_password: mqadmin
qmgr_name: MQ07
stop_on_error: true
...