---
# (c) Copyright IBM Corporation 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

# Playbook file: playbooks/run-mq-start-stop-cmds.yml

# This sample playbook demonstrates how to invoke the runMQCmds role with arguments, to run
# MQ start and stop commands.

- name: Sample playbook to run YAML form MQ start and stop commands specified in a cmds file
  hosts: localhost
  gather_facts: yes

  roles:
  - { role: runMQCmds,
        cmds_file_name: '../cmds_files/mq_start_stop_yaml_form_cmds_file.yml',
        stop_on_error: 'false'
    }
...