---
# (c) Copyright IBM Corporation 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

# Playbook file: playbooks/run_mq_user_yaml_cmds.yml

# Playbook for users to specify argument overrides specific to their environments, and invoke the runMQCmds role 
# against their own MQ cmds file (see supplied playbooks for working examples).)

- name: Playbook to run user specified YAML form MQ commands specified in a cmds file
  hosts: localhost
  gather_facts: yes

  roles:
  - { role: runMQCmds,
        cmds_file_name: '../cmds_files/mq_user_yaml_cmds.yml',
        webserver_addr: ,
        webserver_port: ,
        api_userid: ,
        api_password: ,
        qmgr_name: ,
        stop_on_error:
    }
...