---
# (c) Copyright IBM Corporation 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

# Playbook file: playbooks/run_mq_comms_yaml_cmds.yml

# This sample Ansible playbook demonstrates multiple invocations of the runMQCmds role with arguments, 
# to run YAML form MQ commands (specified in multiple cmds input files) to define resources at
# sending and receiving queue managers.
#
# Specifying multiple invocations of the runMQCmds role in this way allows commands to be run against 
# different queue managers.

- name: Sample playbook to run YAML form MQ for z/OS commands specified in multiple cmds files to define resources at sending and receiving queue managers
  hosts: localhost
  gather_facts: yes

  roles:
  # Invoke runMQcmds role to run MQ commands to define resources on queue manager MQ07 (which is the default queue manager), the sending end.
  - { role: runMQCmds,
        cmds_file_name: '../cmds_files/mq_sending_end_yaml_cmds.yml'
    }

  # Invoke runMQcmds role to run MQ commands to define resources on queue manager MQ08, the receiving end.
  - { role: runMQCmds,
        cmds_file_name: '../cmds_files/mq_receiving_end_yaml_cmds.yml',
        qmgr_name: MQ08
    }
...