---
# (c) Copyright IBM Corporation 2023
# Apache License, Version 2.0 (see https://opensource.org/licenses/Apache-2.0)

# File: roles/runMQCmds/tasks/main.yml

# tasks file for role_runMQCmds

- name: read MQ commands file and save the contents into a variable
  ansible.builtin.slurp:
    src: "{{ cmds_file_name }}"
  delegate_to: localhost
  register: mq_input_cmds

- name: Decode as base 64 string, trim (remove) leading and trailing spaces, and save the YAML format data into a variable
  ansible.builtin.set_fact:
    mq_input_cmds_var: "{{ mq_input_cmds['content'] | b64decode | trim | from_yaml }}"

# Loop for each MQ command, set command in mq_cmd, then prepare and run the command (in the include tasks list).
- name: run mq commands
  ansible.builtin.include_tasks: prepare_and_run_mq_cmd.yml
  loop: "{{ mq_input_cmds_var.mq_commands }}"
  ignore_errors: false
  loop_control:
    loop_var: mq_cmd
  when: ((overallCompCode | int) == 0)
...